/*! Copyright (c) 2021, XAPP AI */
import { expect } from "chai";

import { MOSTLY_CLEAN_SUGGESTED } from "./assets/payloads";
import { generateTextFragmentURL } from "../generateTextFragmentURL";

const STARTS_WITH_ELLIPSES = MOSTLY_CLEAN_SUGGESTED.documents[0];

import * as intent3 from "./assets/intent-kb-results-3.json";


describe(`#${generateTextFragmentURL.name}()`, () => {
    describe(`for undefined`, () => {
        it(`returns undefined`, () => {
            expect(generateTextFragmentURL(undefined, "foo bar")).to.equal(undefined);
            expect(generateTextFragmentURL("https://xapp.ai", undefined)).to.equal("https://xapp.ai");
        });
    });
    describe("with a bad URL", () => {
        it("returns the URL back out", () => {
            expect(generateTextFragmentURL("undefined", "foo bar")).to.equal("undefined");
        });
    });
    describe('with url and document', () => {
        it("returns the correct result", () => {
            expect(generateTextFragmentURL(STARTS_WITH_ELLIPSES.uri, STARTS_WITH_ELLIPSES.document)).to.equal("https://www.consumerfinance.gov/ask-cfpb/what-exactly-happens-when-a-mortgage-lender-checks-my-credit-en-2005#:~:text=to%20be%20smart%20about,a%20mortgage%20or%20during");
            expect(generateTextFragmentURL(STARTS_WITH_ELLIPSES.uri, "about them. As a general")).to.equal("https://www.consumerfinance.gov/ask-cfpb/what-exactly-happens-when-a-mortgage-lender-checks-my-credit-en-2005#:~:text=about%20them.%20As%20a%20general");
            // This one has commas! Oh my
            // https://en.wikipedia.org/wiki/History_of_computing#:~:text=these%20kinds%20of%20statements%20have%20existed%20for%20thousands%20of%20years%2C%20and%20across%20multiple%20civilizations%2C%20as%20shown
            // Generated by chrome extension:
            // https://en.wikipedia.org/wiki/History_of_computing#:~:text=these%20kinds%20of%20statements%20have%20existed%20for%20thousands%20of%20years%2C%20and%20across%20multiple%20civilizations%2C%20as%20shown
            expect(generateTextFragmentURL("https://en.wikipedia.org/wiki/History_of_computing#Early_computation", "These kinds of statements have existed for thousands of years, and across multiple civilizations, as shown")).to.equal("https://en.wikipedia.org/wiki/History_of_computing#:~:text=These%20kinds%20of%20statements,multiple%20civilizations%2C%20as%20shown");
        });
        describe("when the document has a lot of new lines", () => {
            it("returns the correct result", () => {
                const suggested = intent3.knowledgeBaseResult.suggested;
                const docs = intent3.knowledgeBaseResult.documents;

                const url1 = generateTextFragmentURL(docs[1].uri, docs[1].document);
                expect(url1).to.exist;

                const url2 = generateTextFragmentURL(docs[2].uri, docs[2].document);
                expect(url2).to.exist;
                expect(url2).to.equal("https://www.barringerbrothers.com/about-us/#:~:text=Business%20Bureau.%20We%20work,trust%20our%20team%20to");

                const url5 = generateTextFragmentURL(docs[5].uri, docs[5].document);
                expect(url5).to.exist;

                const suggestedURL = generateTextFragmentURL(suggested[0].uri, suggested[0].document);
                expect(suggestedURL).to.exist;
                expect(suggestedURL).to.equal("https://www.barringerbrothers.com/about-us/#:~:text=From%20storm%20damage%20roof,request%20your%20free%20estimate.");
            });
        });
    });
});